(() => {
 const O=window.OxygeNTools;
 O.register('image-pdf',host=>{
  host.innerHTML=`<section class="ot-panel"><div class="ot-drop" id="pdf-drop"><div><strong>🖼️ Arrastra tus imágenes aquí</strong><br>o selecciona archivos desde tu dispositivo<br><span class="ot-hint">JPG, PNG, WebP, GIF y otros formatos compatibles con el navegador</span></div><input id="pdf-files" type="file" accept="image/png,image/jpeg,image/webp,image/gif,image/bmp,image/avif" multiple hidden></div><div class="ot-file-list" id="pdf-list"></div><div class="ot-fields" style="margin-top:18px"><div class="ot-field"><label for="pdf-page">Tamaño de página</label><select class="ot-select" id="pdf-page"><option value="a4">A4</option><option value="letter">Carta</option><option value="legal">Oficio</option><option value="a5">A5</option><option value="auto">Automático</option></select></div><div class="ot-field"><label for="pdf-orientation">Orientación</label><select class="ot-select" id="pdf-orientation"><option value="portrait">Vertical</option><option value="landscape">Horizontal</option></select></div><div class="ot-field"><label for="pdf-margin">Margen (mm)</label><input class="ot-input" id="pdf-margin" type="number" min="0" max="35" value="10"></div><div class="ot-field"><label for="pdf-quality">Calidad</label><select class="ot-select" id="pdf-quality"><option value="0.62">Ligera</option><option value="0.82" selected>Alta</option><option value="0.95">Máxima</option></select></div><div class="ot-field"><label for="pdf-bg">Fondo de página</label><input class="ot-input" id="pdf-bg" type="color" value="#ffffff"></div><div class="ot-field"><label>Ajuste de imagen</label><select class="ot-select" id="pdf-fit"><option value="contain">Contener (sin recortar)</option><option value="cover">Rellenar (recorta bordes)</option></select></div><div class="ot-field"><label class="ot-check"><input type="checkbox" id="pdf-bw"> Blanco y negro</label></div></div><h2 style="font-size:1rem;margin:20px 0 6px">Previsualización de página</h2><div class="ot-preview" id="pdf-preview"><span class="ot-hint">Agrega imágenes para previsualizar la primera página.</span></div><p class="ot-hint">Arrastra las miniaturas para cambiar el orden. Cada imagen ocupará una página.</p><div class="ot-actions"><button class="ot-btn primary" id="pdf-create" type="button">Generar PDF</button><button class="ot-btn ghost" id="pdf-reset" type="button">Limpiar selección</button></div><div class="ot-message" aria-live="polite"></div></section>`;
  const $=s=>O.$(s,host);let items=[];const fileInput=$('#pdf-files');
  function paintList(){const list=$('#pdf-list');list.innerHTML=items.map((it,i)=>`<div class="ot-file-item" draggable="true" data-index="${i}"><img src="${it.url}" alt="Vista previa de ${O.esc(it.file.name)}"><span class="file-info">${O.esc(it.file.name)}<br><span class="ot-hint">${O.bytes(it.file.size)}</span></span><button class="ot-btn ghost" data-remove="${i}" aria-label="Quitar ${O.esc(it.file.name)}">×</button></div>`).join('');renderPreview();}
  function dimensions(img){const maps={a4:[210,297],letter:[215.9,279.4],legal:[215.9,355.6],a5:[148,210]};let [w,h]=maps[$('#pdf-page').value]||[Math.min(img.naturalWidth*.264583,420),Math.min(img.naturalHeight*.264583,420)];if($('#pdf-page').value==='auto'){const scale=Math.min(1,420/Math.max(w,h));w*=scale;h*=scale;}if($('#pdf-orientation').value==='landscape'&&w<h||$('#pdf-orientation').value==='portrait'&&w>h)[w,h]=[h,w];return [w,h];}
  function drawPage(ctx,img,w,h,scale){const margin=Math.min(35,Math.max(0,Number($('#pdf-margin').value)||0))*scale,areaW=Math.max(1,w-2*margin),areaH=Math.max(1,h-2*margin);ctx.fillStyle=$('#pdf-bg').value;ctx.fillRect(0,0,w,h);if($('#pdf-bw').checked)ctx.filter='grayscale(1)';const ratio=$('#pdf-fit').value==='cover'?Math.max(areaW/img.naturalWidth,areaH/img.naturalHeight):Math.min(areaW/img.naturalWidth,areaH/img.naturalHeight),dw=img.naturalWidth*ratio,dh=img.naturalHeight*ratio,dx=margin+(areaW-dw)/2,dy=margin+(areaH-dh)/2;ctx.save();ctx.beginPath();ctx.rect(margin,margin,areaW,areaH);ctx.clip();ctx.drawImage(img,dx,dy,dw,dh);ctx.restore();ctx.filter='none';}
  function renderPreview(){if(!items.length){$('#pdf-preview').innerHTML='<span class="ot-hint">Agrega imágenes para previsualizar la primera página.</span>';return;}const img=items[0].img,[pw,ph]=dimensions(img);const scale=Math.min(600/pw,720/ph);const c=document.createElement('canvas');c.width=Math.round(pw*scale);c.height=Math.round(ph*scale);drawPage(c.getContext('2d'),img,c.width,c.height,scale);$('#pdf-preview').replaceChildren(c);}
  async function addFiles(files){for(const file of files){if(!file.type.startsWith('image/'))continue;try{const loaded=await O.imageFromFile(file);items.push({file,img:loaded.img,url:loaded.url});}catch(err){O.msg(host,err.message);}}paintList();}
  $('#pdf-drop').addEventListener('click',e=>{if(e.target!==fileInput)fileInput.click();});fileInput.addEventListener('change',()=>addFiles([...fileInput.files]));
  const drop=$('#pdf-drop');drop.addEventListener('dragover',e=>{e.preventDefault();drop.classList.add('drag');});drop.addEventListener('dragleave',()=>drop.classList.remove('drag'));drop.addEventListener('drop',e=>{e.preventDefault();drop.classList.remove('drag');addFiles([...e.dataTransfer.files]);});
  $('#pdf-list').addEventListener('click',e=>{const btn=e.target.closest('[data-remove]');if(btn){const i=+btn.dataset.remove;URL.revokeObjectURL(items[i].url);items.splice(i,1);paintList();}});
  let dragIndex=null;$('#pdf-list').addEventListener('dragstart',e=>{const row=e.target.closest('.ot-file-item');if(row){dragIndex=+row.dataset.index;e.dataTransfer.effectAllowed='move';}});$('#pdf-list').addEventListener('dragover',e=>{if(e.target.closest('.ot-file-item'))e.preventDefault();});$('#pdf-list').addEventListener('drop',e=>{const row=e.target.closest('.ot-file-item');if(!row||dragIndex===null)return;e.preventDefault();const to=+row.dataset.index,[moved]=items.splice(dragIndex,1);items.splice(to,0,moved);dragIndex=null;paintList();});
  ['pdf-page','pdf-orientation','pdf-margin','pdf-bg','pdf-fit','pdf-bw'].forEach(id=>$('#'+id).addEventListener('input',renderPreview));
  $('#pdf-reset').addEventListener('click',()=>{items.forEach(x=>URL.revokeObjectURL(x.url));items=[];fileInput.value='';paintList();O.clearMsg(host);});
  $('#pdf-create').addEventListener('click',async()=>{if(!items.length)return O.msg(host,'Selecciona al menos una imagen.');const btn=$('#pdf-create');btn.disabled=true;btn.textContent='Preparando PDF…';try{await O.loadScript('https://cdn.jsdelivr.net/npm/jspdf@2.5.2/dist/jspdf.umd.min.js');const {jsPDF}=window.jspdf||{};if(!jsPDF)throw new Error('No se pudo iniciar el creador de PDF.');let pdf=null;for(let i=0;i<items.length;i++){const item=items[i],[w,h]=dimensions(item.img);if(!pdf)pdf=new jsPDF({orientation:w>h?'landscape':'portrait',unit:'mm',format:[w,h],compress:true});else pdf.addPage([w,h],w>h?'landscape':'portrait');const scale=3,c=document.createElement('canvas');c.width=Math.round(w*scale);c.height=Math.round(h*scale);drawPage(c.getContext('2d'),item.img,c.width,c.height,scale);const data=c.toDataURL('image/jpeg',Number($('#pdf-quality').value));pdf.addImage(data,'JPEG',0,0,w,h,undefined,'FAST');}pdf.save('oxygetools-imagenes.pdf');O.msg(host,'PDF creado. La descarga comenzó.','success');}catch(err){console.error(err);O.msg(host,err.message||'No se pudo generar el PDF. Verifica tus imágenes e inténtalo de nuevo.');}finally{btn.disabled=false;btn.textContent='Generar PDF';}});
 });
})();
