(() => {const O=window.OxygeNTools;O.register('convert',host=>{
 host.innerHTML=`<section class="ot-panel"><label class="ot-drop" for="conv-files"><span><strong>🔄 Selecciona o arrastra varias imágenes</strong><br><span class="ot-hint">Puedes elegir varias. PNG, JPG/JPEG, WebP y otros formatos de imagen compatibles.</span></span></label><input id="conv-files" type="file" accept="image/png,image/jpeg,image/webp,image/gif,image/bmp,image/avif" multiple hidden><div class="ot-fields" style="margin-top:16px"><div class="ot-field"><label for="conv-format">Formato de salida</label><select class="ot-select" id="conv-format"><option value="image/png">PNG</option><option value="image/jpeg">JPG</option><option value="image/webp">WebP</option></select></div><div class="ot-field"><label for="conv-quality">Calidad JPG/WebP <span id="conv-q">85%</span></label><input class="ot-input" id="conv-quality" type="range" min="10" max="100" value="85"></div></div><div class="ot-file-list" id="conv-list"><div class="ot-empty-results">Tus imágenes seleccionadas aparecerán aquí.</div></div><div class="ot-actions"><button class="ot-btn primary" id="conv-go">Convertir todas</button><button class="ot-btn" id="conv-zip" disabled>Descargar ZIP</button><button class="ot-btn ghost" id="conv-clear">Limpiar</button></div><div class="ot-status" id="conv-status" aria-live="polite"></div><div class="ot-message" aria-live="polite"></div></section>`;
 const $=s=>O.$(s,host);let files=[],results=[];
 function render(){const list=$('#conv-list');if(!files.length){list.innerHTML='<div class="ot-empty-results">Tus imágenes seleccionadas aparecerán aquí.</div>';return;}list.innerHTML=files.map((x,i)=>`<div class="ot-file-item"><img src="${x.url}" alt=""><span class="file-info">${O.esc(x.file.name)}<br><span class="ot-hint">${O.bytes(x.file.size)} · ${x.img.naturalWidth} × ${x.img.naturalHeight}px</span><span class="conv-result" data-result="${i}"></span></span><button class="ot-btn ghost" data-remove="${i}" aria-label="Quitar ${O.esc(x.file.name)}">×</button></div>`).join('');}
 async function add(list){for(const f of list){if(!f.type.startsWith('image/'))continue;try{const v=await O.imageFromFile(f);files.push({file:f,img:v.img,url:v.url});}catch(e){O.msg(host,e.message);}}results=[];$('#conv-zip').disabled=true;render();}
 $('#conv-files').addEventListener('change',e=>add([...e.target.files]));const drop=$('.ot-drop');drop.addEventListener('dragover',e=>{e.preventDefault();drop.classList.add('drag')});drop.addEventListener('dragleave',()=>drop.classList.remove('drag'));drop.addEventListener('drop',e=>{e.preventDefault();drop.classList.remove('drag');add([...e.dataTransfer.files])});
 $('#conv-quality').addEventListener('input',e=>$('#conv-q').textContent=`${e.target.value}%`);$('#conv-list').addEventListener('click',e=>{const b=e.target.closest('[data-remove]');if(b){const i=+b.dataset.remove;URL.revokeObjectURL(files[i].url);files.splice(i,1);results=[];$('#conv-zip').disabled=true;render();}});
 $('#conv-go').addEventListener('click',async()=>{if(!files.length)return O.msg(host,'Selecciona al menos una imagen.');results=[];const btn=$('#conv-go'),type=$('#conv-format').value,q=Number($('#conv-quality').value)/100,ext=type.split('/')[1].replace('jpeg','jpg');btn.disabled=true;try{for(let i=0;i<files.length;i++){const item=files[i],c=document.createElement('canvas');c.width=item.img.naturalWidth;c.height=item.img.naturalHeight;const ctx=c.getContext('2d');if(type==='image/jpeg'){ctx.fillStyle='#fff';ctx.fillRect(0,0,c.width,c.height);}ctx.drawImage(item.img,0,0);const blob=await O.canvasBlob(c,type,q);const name=`${O.safeFilename(item.file.name)}.${ext}`;results[i]={blob,name};const status=O.$(`[data-result="${i}"]`,host);if(status)status.innerHTML=`<br><span class="ot-hint">${O.bytes(blob.size)} · listo</span> <button class="ot-btn" type="button" data-download="${i}">Descargar</button>`;$('#conv-status').textContent=`Convertidas ${i+1} de ${files.length}…`; }$('#conv-zip').disabled=false;O.msg(host,'Conversión terminada. Descarga cada archivo o todos juntos en ZIP.','success');}catch(err){console.error(err);O.msg(host,'No se pudo convertir uno de los archivos. Prueba con una imagen distinta.');}finally{btn.disabled=false;$('#conv-status').textContent='';}});
 $('#conv-list').addEventListener('click',e=>{const link=e.target.closest('[data-download]');if(link){const i=+link.dataset.download;if(results[i])O.download(results[i].blob,results[i].name);}});
 $('#conv-zip').addEventListener('click',async()=>{if(!results.length)return;const b=$('#conv-zip');b.disabled=true;b.textContent='Preparando ZIP…';try{await O.loadScript('https://cdn.jsdelivr.net/npm/jszip@3.10.1/dist/jszip.min.js');const zip=new JSZip();results.forEach((r,i)=>{if(r)zip.file(r.name,r.blob);});const blob=await zip.generateAsync({type:'blob'});O.download(blob,'oxygetools-imagenes.zip');}catch(e){console.error(e);O.msg(host,'No se pudo preparar el ZIP. Descarga los archivos por separado.');}finally{b.disabled=false;b.textContent='Descargar ZIP';}});
 $('#conv-clear').addEventListener('click',()=>{files.forEach(f=>URL.revokeObjectURL(f.url));files=[];results=[];$('#conv-files').value='';$('#conv-zip').disabled=true;render();O.clearMsg(host);});
 });})();
