(() => {
  const entry = (slug,title,icon,description,tags,category) => ({slug,title,icon,description,tags,category});
  window.OxygeNToolsCatalog = [
    entry('convert','Convertidor de imágenes','🔄','Convierte imágenes a PNG, JPG o WebP en lote.','imagen png jpg jpeg webp convertir','Imágenes'),
    entry('compress','Compresor de imágenes','🗜️','Reduce el peso de tus imágenes sin subirlas.','imagen jpg jpeg webp png comprimir calidad','Imágenes'),
    entry('resize','Redimensionador','↔️','Cambia dimensiones conservando la proporción.','imagen tamaño ancho alto redimensionar','Imágenes'),
    entry('image-editor','Editor de imagen básico','✏️','Aplica ajustes rápidos y exporta desde tu navegador.','imagen editar brillo contraste blanco y negro','Imágenes'),
    entry('colors','Selector de colores','🎨','Explora HEX, RGB, HSL y armonías cromáticas.','color picker hex rgb hsl complementario','Diseño'),
    entry('image-pdf','Imagen → PDF','📄','Organiza imágenes y conviértelas en un PDF.','imagen pdf documento página','Documentos'),
    entry('pdf-merge','Unir PDF','📚','Combina archivos PDF localmente.','pdf combinar unir documentos','Documentos'),
    entry('pdf-split','Dividir PDF','✂️','Extrae páginas de un PDF a otro archivo.','pdf dividir separar páginas','Documentos'),
    entry('text','Herramientas de texto','🔤','Cuenta palabras, caracteres y líneas.','texto palabras caracteres contador','Documentos'),
    entry('qr','Generador QR','▦','Crea códigos QR personalizables y descargables.','qr código url texto logo','Código y web'),
    entry('barcode','Códigos de barras','▥','Genera códigos de barras desde el navegador.','barcode código barras ean code128','Código y web'),
    entry('html','Generador de HTML básico','</>','Arma una estructura HTML descargable.','html código web boilerplate','Código y web'),
    entry('json','JSON Formatter','{ }','Valida, formatea y minifica JSON.','json validar formatear minificar','Código y web'),
    entry('base64','Base64 Encoder/Decoder','⇄','Codifica y decodifica texto Unicode.','base64 encode decode texto','Código y web'),
    entry('url','URL Encoder/Decoder','🔗','Codifica o decodifica texto para URLs.','url encode decode enlace','Código y web'),
    entry('uuid','Generador de UUID','🆔','Genera identificadores aleatorios seguros.','uuid identificador crypto','Utilidades'),
    entry('palette','Generador de paletas','🌈','Crea combinaciones desde un color base.','paleta complementarios triádicos análogos','Diseño'),
    entry('gradient','Gradiente CSS','🌅','Diseña degradados y copia su CSS.','css gradiente linear gradient','Diseño'),
    entry('shadow','Generador de sombras CSS','◫','Ajusta y copia una sombra CSS.','css box shadow sombra','Diseño'),
    entry('favicon','Generador de favicon','🧿','Crea un favicon PNG a partir de texto o imagen.','favicon icono web imagen','Diseño'),
    entry('pixel','Editor pixel-art','🟪','Dibuja sprites en un lienzo pixelado.','pixel art canvas 16 24 32','Diseño'),
    entry('password','Generador de contraseñas','🔐','Crea contraseñas localmente con aleatoriedad segura.','contraseña password seguridad crypto','Utilidades'),
    entry('hash','Hash Generator','#️⃣','Calcula SHA-256 en este dispositivo.','hash sha256 criptografía','Utilidades'),
    entry('random-text','Generador de texto aleatorio','🎲','Crea texto de prueba sin conexión.','texto aleatorio lorem ipsum','Utilidades'),
    entry('stopwatch','Cronómetro','⏱️','Cronómetro sencillo con controles accesibles.','tiempo cronómetro stopwatch','Utilidades'),
    entry('units','Conversor de unidades','📐','Convierte longitud, masa y temperatura.','unidades conversor cm m kg celsius','Utilidades')
  ];
  window.OxygeNToolsMeta = Object.fromEntries([
    ['qr','Generador QR','Crea un QR para texto o una URL, con opciones de personalización.'],
    ['image-pdf','Imagen → PDF','Ordena tus imágenes, previsualiza las páginas y crea el PDF localmente.'],
    ['compress','Compresor de imágenes','Ajusta dimensiones y calidad; compara el tamaño antes de descargar.'],
    ['convert','Convertidor de imágenes','Convierte varias imágenes de una sola vez y descarga cada resultado o un ZIP.'],
    ['resize','Redimensionador','Define el tamaño exacto, bloquea la proporción o escala en porcentaje.'],
    ['colors','Selector de colores','Elige un color y consulta sus valores y armonías.'],
    ['palette','Generador de paletas','Genera armonías cromáticas y tonos claros y oscuros.'],
    ['json','JSON Formatter','Valida, formatea, minifica y copia JSON con mensajes claros.'],
    ['base64','Base64 Encoder/Decoder','Codifica y decodifica texto Unicode en tu navegador.'],
    ['url','URL Encoder/Decoder','Codifica o decodifica componentes de URL.'],
    ['uuid','Generador de UUID','Genera 1, 5, 10, 50 o 100 identificadores.'],
    ['password','Generador de contraseñas','Configura una contraseña aleatoria segura que no se almacena ni se envía.'],
    ['text','Contador de texto','Cuenta caracteres, palabras, líneas y párrafos mientras escribes.'],
    ['pixel','Editor Pixel-Art','Dibuja en una cuadrícula 16×16, 24×24 o 32×32 y exporta PNG.'],
    ['barcode','Generador de códigos de barras','Crea y descarga códigos de barras en PNG o SVG.'],
    ['html','Generador de HTML básico','Genera un documento HTML inicial listo para descargar.'],
    ['gradient','Generador de gradientes CSS','Ajusta colores y ángulo; previsualiza y copia el CSS.'],
    ['shadow','Generador de sombras CSS','Controla desplazamiento, desenfoque, expansión y color.'],
    ['favicon','Generador de favicon','Crea un icono PNG cuadrado a partir de un emoji, texto o imagen.'],
    ['image-editor','Editor de imagen básico','Ajusta brillo, contraste, saturación y escala de grises.'],
    ['pdf-merge','Unir PDF','Combina varios PDF directamente en el navegador.'],
    ['pdf-split','Dividir PDF','Elige páginas de un PDF y crea un nuevo documento.'],
    ['hash','Hash Generator','Calcula el hash SHA-256 de texto localmente.'],
    ['random-text','Generador de texto aleatorio','Crea texto de prueba al instante.'],
    ['stopwatch','Cronómetro','Inicia, pausa, reinicia y registra vueltas.'],
    ['units','Conversor de unidades','Convierte longitud, masa y temperatura.']
  ].map(([slug,title,description])=>[slug,{title,description}]));
})();
